#!/usr/bin/env sh

# Visual Studio Code dark color scheme for fzf

# Generated using https://vitormv.github.io/fzf-themes#eyJjb2xvcnMiOiJmZzojZDRkNGQ0LGZnKzojZDRkNGQ0LGJnOiMxZjFmMWYsYmcrOiMyMjIyMjIsaGw6IzYwOGI0ZSxobCs6I0M1ODZDMCxpbmZvOiNDNTg2QzAsbWFya2VyOiNDNTg2QzAscHJvbXB0OiNDNTg2QzAsc3Bpbm5lcjojQzU4NkMwLHBvaW50ZXI6I0M1ODZDMCxoZWFkZXI6IzYwOGI0ZSxib3JkZXI6IzgwODA4MCxsYWJlbDojQzU4NkMwLHF1ZXJ5OiNkNGQ0ZDQifQ==

# .profile, .bash_profile, .zshenv

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS"'
  --color=fg:#d4d4d4,fg+:#d4d4d4,bg:#1f1f1f,bg+:#222222
  --color=hl:#608b4e,hl+:#C586C0,info:#C586C0,marker:#C586C0
  --color=prompt:#C586C0,spinner:#C586C0,pointer:#C586C0,header:#608b4e
  --color=border:#808080,label:#C586C0,query:#d4d4d4'
