#!/usr/bin/env sh

# Visual Studio Code light color scheme for fzf

# Generated using https://vitormv.github.io/fzf-themes#eyJjb2xvcnMiOiJmZzojMDAwMDAwLGZnKzojMDAwMDAwLGJnOiNGRkZGRkYsYmcrOiNGM0YzRjMsaGw6IzAwODAwMCxobCs6I0FGMDBEQixpbmZvOiNBRjAwREIsbWFya2VyOiNBRjAwREIscHJvbXB0OiNBRjAwREIsc3Bpbm5lcjojQUYwMERCLHBvaW50ZXI6I0FGMDBEQixoZWFkZXI6IzAwODAwMCxib3JkZXI6IzAwMDAwMCxsYWJlbDojQUYwMERCLHF1ZXJ5OiMwMDAwMDAifQ==

# .profile, .bash_profile, .zshenv

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS"'
  --color=fg:#000000,fg+:#000000,bg:#FFFFFF,bg+:#F3F3F3
  --color=hl:#008000,hl+:#AF00DB,info:#AF00DB,marker:#AF00DB
  --color=prompt:#AF00DB,spinner:#AF00DB,pointer:#AF00DB,header:#008000
  --color=border:#000000,label:#AF00DB,query:#000000'
