#!/usr/bin/env sh

# .login, .bash_login, .zlogin:

# set Linux console colors
if [ "$TERM" = "linux" ]; then
  printf "\033]P0%s" "1f1f1f"
  printf "\033]P1%s" "f44747"
  printf "\033]P2%s" "608b4e"
  printf "\033]P3%s" "dcdcaa"
  printf "\033]P4%s" "569cd6"
  printf "\033]P5%s" "c678dd"
  printf "\033]P6%s" "56b6c2"
  printf "\033]P7%s" "d4d4d4"
  printf "\033]P8%s" "808080"
  printf "\033]P9%s" "f44747"
  printf "\033]PA%s" "608b4e"
  printf "\033]PB%s" "dcdcaa"
  printf "\033]PC%s" "569cd6"
  printf "\033]PD%s" "c678dd"
  printf "\033]PE%s" "56b6c2"
  printf "\033]PF%s" "d4d4d4"
fi

# .logout, .bash_logout, .zlogout:

if [ "$TERM" = "linux" ]; then
  reset
fi
